apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jryantiermore/bda_ca3_2.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-faceapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
